Repository dotnet/vscode-csharp, pull requests merged in 2023-09, with the labels that each got.

#6359 Add 'when' to 'clr' debugger for Windows
  package.json
Labels: Debugger, enhancement

#6380 Fix isSubfolderOf to correctly determine if a folder is a subfolder
  omnisharptest/omnisharpJestTests/common.test.ts
  src/common.ts
  src/omnisharpWorkspaceDebugInformationProvider.ts
Labels: OmniSharp

#6432 Add support for multilaunch for Blazorwasm
  src/shared/dotnetConfigurationProvider.ts
Labels: Bug, Debugger
